/*
 * pm-app -- userspace driver for the PE-array program manager on VCU128/MicroBlaze.
 *
 * program_manager_top is a free-running (ap_ctrl_none) HLS kernel with an
 * AXI-Lite slave and nothing else: no ap_start to assert, no interrupt to wait
 * on, no DMA. It begins evaluating the grid the moment reset releases. All we
 * do is write a command, strobe valid, and poll the busy bitmap.
 *
 * The register window is a plain mmap of /dev/mem at the IP's base address.
 * There is no interrupt, so UIO would buy nothing over this.
 *
 * This mirrors the Alveo host in HW_prototype/boards/u280/host_runtime.cpp and
 * the C-simulation testbench in vitis_hls/program_manager/test/main_csim.cpp --
 * the occupancy map it prints should match what `make csim` prints for the same
 * sequence.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/mman.h>
#include <time.h>
#include <readline/readline.h>
#include <readline/history.h>

/* -------------------------------------------------------------------------
 * REGISTER OFFSETS -- verified against the HLS-generated header:
 *   vitis_hls/IPs/program_manager/drivers/program_manager_top_v1_0/src/
 *       xprogram_manager_top_hw.h   (Vitis HLS 2024.2)
 *
 * Scalars sit on 8-byte strides (each has a reserved word after it).
 *
 * busy_map_out_bits is an ARRAY, which HLS maps as a memory region rather than
 * a register, and it does NOT follow immediately after busy_mask_out: 0x54 is
 * busy_mask_out's ap_vld bit and 0x58-0x5c are reserved, so the map starts at
 * 0x60 and spans 0x60-0x67 (2 words of 32b).
 * ------------------------------------------------------------------------- */
#define REG_MODE            0x10
#define REG_TARGET_MODE     0x18
#define REG_PE_X            0x20
#define REG_PE_Y            0x28
#define REG_CLUSTER_ID      0x30
#define REG_BANK_ID         0x38
#define REG_CYCLES          0x40
#define REG_VALID           0x48
#define REG_BUSY_MASK       0x50   /* 0x54 = busy_mask_out ap_vld (clear on read) */
#define REG_BUSY_MAP_BASE   0x60   /* busy_map_out_bits[2], 0x60-0x67 */

/* cfg_status is declared last in the HLS port list, so it should land after the
 * busy map. THIS OFFSET IS A PREDICTION until the IP is rebuilt -- confirm it
 * against the regenerated xprogram_manager_top_hw.h, along with whether the new
 * scalar pushed REG_BUSY_MAP_BASE off 0x60. A wrong guess here only breaks the
 * post-upload verification, which warns rather than aborts for exactly that
 * reason; dispatch itself does not read this register. */
#define REG_CFG_STATUS      0x68
#define CFG_STATUS_LOADED   0x80000000u   /* the host's cluster table is in force */

/* Mirrors the enums in vitis_hls/program_manager/include/dispatch.hpp */
enum { PM_IDLE = 0, PM_RUN = 1, PM_RESET = 2, PM_CONFIG = 3 };
enum { TARGET_SINGLE_PE = 0, TARGET_CLUSTER = 1 };

/* Under PM_CONFIG, pe_x = CFG_COMMIT means "publish the table written so far"
 * rather than "configure PE 255". Uploading and publishing are separate so the
 * grid never dispatches against a half-written table. */
#define CFG_COMMIT 255

/* DIM_X / DIM_Y / MAX_BANKS / NUM_CLUSTERS come from pm_layout.h, which is
 * generated by `make layout-header` in vitis_hls/ from the same GRID_DIM the
 * bitstream was built with. Do not redefine them here -- that is exactly the
 * drift the generated header exists to prevent. */
#include "pm_layout.h"
#include "layout.h"

#define DEFAULT_LAYOUT_FILE "/etc/pm-layout.conf"

#define NUM_WORDS ((DIM_X * DIM_Y + 31) / 32)

/* /pl-bus/program_manager_top@40010000, reg = <0x40010000 0x10000> */
#define PM_BASE_ADDR 0x40010000UL
#define PM_MAP_SIZE  0x1000UL

/* 100 MHz fabric clock (vivado/VCU128_microblaze_bd.tcl), but the free-running
 * loop synthesized at II=2 (see VITIS_LOOP_49_1 in csynth.rpt), so the PE
 * countdown advances once every two clocks. */
#define PM_CLK_HZ    100000000UL
#define PM_LOOP_II   2UL
#define PM_TICK_HZ   (PM_CLK_HZ / PM_LOOP_II)
#define SECONDS(s)   ((uint32_t)(PM_TICK_HZ * (s)))

static volatile uint32_t *regs;

/* The layout currently in force in the hardware. Everything host-side that used
 * to assume the compiled-in left/right split now reads this instead. */
static struct pm_layout g_layout;

static void reg_write(uint32_t off, uint32_t val) { regs[off / 4] = val; }
static uint32_t reg_read(uint32_t off)            { return regs[off / 4]; }

/* ---------------------------------------------------------------------------
 * Command layer
 * ------------------------------------------------------------------------- */
/* cycles is Read/Write, so a readback distinguishes "bus is dead" from
 * "everything works but the dispatch was too short to catch". */
static int bus_selftest(void)
{
    static const uint32_t pat[] = { 0xdeadbeefu, 0x55555555u, 0u };
    unsigned i;

    for (i = 0; i < sizeof(pat) / sizeof(pat[0]); i++) {
        uint32_t rb;
        reg_write(REG_CYCLES, pat[i]);
        rb = reg_read(REG_CYCLES);
        if (rb != pat[i]) {
            fprintf(stderr, "AXI-Lite readback failed at 0x%02x: wrote 0x%08x, read 0x%08x\n",
                    REG_CYCLES, pat[i], rb);
            fprintf(stderr, "the IP is not responding -- check the bitstream is loaded "
                            "and the interconnect address map matches 0x%lx.\n", PM_BASE_ADDR);
            return -1;
        }
    }
    printf("AXI-Lite readback OK.\n");
    return 0;
}

static void issue_command(uint8_t mode, uint8_t target_mode,
                          uint8_t pe_x, uint8_t pe_y, uint8_t cluster_id,
                          uint8_t bank_id, uint32_t cycles)
{
    reg_write(REG_MODE,        mode);
    reg_write(REG_TARGET_MODE, target_mode);
    reg_write(REG_PE_X,        pe_x);
    reg_write(REG_PE_Y,        pe_y);
    reg_write(REG_CLUSTER_ID,  cluster_id);
    reg_write(REG_BANK_ID,     bank_id);
    reg_write(REG_CYCLES,      cycles);

    /* The kernel edge-detects valid_signal; only the 0->1 transition latches a
     * command. Two AXI-Lite writes are many kernel cycles apart, so the high
     * period is comfortably long enough to be sampled. */
    reg_write(REG_VALID, 1);
    reg_write(REG_VALID, 0);
}

static int pe_is_busy(int x, int y)
{
    int flat = y * DIM_X + x;
    uint32_t word = reg_read(REG_BUSY_MAP_BASE + (flat / 32) * 4);
    return (word >> (flat % 32)) & 1u;
}

static void read_map(uint32_t *w)
{
    int i;
    for (i = 0; i < NUM_WORDS; i++)
        w[i] = reg_read(REG_BUSY_MAP_BASE + i * 4);
}

static int map_bit(const uint32_t *w, int x, int y)
{
    int flat = y * DIM_X + x;
    return (w[flat / 32] >> (flat % 32)) & 1u;
}

static int in_grid(int x, int y)
{
    return x >= 0 && x < DIM_X && y >= 0 && y < DIM_Y;
}

/* ---------------------------------------------------------------------------
 * Cluster table upload
 *
 * Cluster membership is no longer a function of position -- it is whatever the
 * layout file says. The manager holds the table in registers; we write it one PE
 * at a time and then commit.
 * ------------------------------------------------------------------------- */
static void push_layout(const struct pm_layout *l)
{
    int x, y;

    for (y = 0; y < DIM_Y; y++)
        for (x = 0; x < DIM_X; x++)
            issue_command(PM_CONFIG, TARGET_SINGLE_PE, (uint8_t)x, (uint8_t)y,
                          l->cluster[y][x], l->banks[y][x], 0);

    issue_command(PM_CONFIG, TARGET_SINGLE_PE, CFG_COMMIT, 0, 0, 0, 0);
}

/* Reads the table back out of the hardware rather than assuming the writes
 * landed. Returns the number of mismatches. */
static int verify_layout(const struct pm_layout *l)
{
    int x, y, bad = 0;
    uint32_t st;

    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            /* cfg_status reports the PE that pe_x/pe_y currently address. */
            reg_write(REG_PE_X, (uint32_t)x);
            reg_write(REG_PE_Y, (uint32_t)y);
            st = reg_read(REG_CFG_STATUS);

            if (((st >> 8) & 0xff) != l->cluster[y][x] ||
                (st & 0xff)        != l->banks[y][x]) {
                if (bad < 4)
                    fprintf(stderr, "   PE (%d,%d): wrote cluster %u banks %u, "
                                    "read back cluster %u banks %u\n",
                            x, y, l->cluster[y][x], l->banks[y][x],
                            (unsigned)((st >> 8) & 0xff), (unsigned)(st & 0xff));
                bad++;
            }
        }
    }

    st = reg_read(REG_CFG_STATUS);
    if (!(st & CFG_STATUS_LOADED)) {
        fprintf(stderr, "   commit did not take: cfg_loaded is still clear\n");
        bad++;
    }
    return bad;
}

/* Upload, verify, and adopt. A verification failure is reported loudly but not
 * treated as fatal: the most likely cause is REG_CFG_STATUS being at the wrong
 * offset, which does not affect dispatch at all, and refusing to start would
 * leave no way to investigate from the board. */
static void apply_layout(const struct pm_layout *l)
{
    int bad;

    push_layout(l);
    bad = verify_layout(l);
    g_layout = *l;

    if (bad) {
        fprintf(stderr, "WARNING: %d of %d PEs did not read back as written.\n"
                        "         If ALL of them differ, REG_CFG_STATUS (0x%02x) is "
                        "probably wrong --\n"
                        "         check xprogram_manager_top_hw.h. Dispatch is "
                        "unaffected either way;\n"
                        "         use `run` and `map` to see what the grid actually "
                        "does.\n",
                bad, DIM_X * DIM_Y, REG_CFG_STATUS);
    } else {
        printf("Cluster table uploaded and verified (%d PEs).\n", DIM_X * DIM_Y);
    }
    layout_print(l);
}

/* The IP reports no accept/reject status: a busy PE ignores a command and an
 * unloaded bank is refused, both silently. Sampling the map either side of the
 * strobe separates the cases exactly -- a PE that was idle and is now busy
 * accepted, anything else did not. Only valid for dispatches long enough to
 * outlive the readback; sub-millisecond runs look refused. */
static void report_accept(const uint32_t *before, const uint32_t *after,
                          int single, int tx, int ty, int cluster)
{
    int x, y, started = 0, was_busy = 0, refused = 0;

    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            int targeted = single ? (x == tx && y == ty)
                                  : (g_layout.cluster[y][x] == cluster);
            if (!targeted)
                continue;
            if (map_bit(before, x, y))      was_busy++;
            else if (map_bit(after, x, y))  started++;
            else                            refused++;
        }
    }

    printf("   accepted %d", started);
    if (was_busy) printf(", %d already busy", was_busy);
    if (refused)  printf(", %d refused (bank not loaded, or a spare PE)", refused);
    printf("\n");
}

/* Wraps issue_command with the before/after sampling. */
static void run_and_report(int single, int x, int y, int cluster,
                           int bank, uint32_t cycles)
{
    uint32_t before[NUM_WORDS], after[NUM_WORDS];

    read_map(before);
    issue_command(PM_RUN, single ? TARGET_SINGLE_PE : TARGET_CLUSTER,
                  (uint8_t)x, (uint8_t)y, (uint8_t)cluster, (uint8_t)bank, cycles);
    read_map(after);
    report_accept(before, after, single, x, y, cluster);
}

static double elapsed_since(const struct timespec *t0)
{
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    return (now.tv_sec - t0->tv_sec) + (now.tv_nsec - t0->tv_nsec) / 1e9;
}

/* Bounded, unlike the Alveo host's unbounded spin. Reports how long the PE was
 * actually seen busy, which is what tells you whether a dispatch was observable
 * at all. */
static int wait_until_idle(int x, int y, double timeout_s)
{
    struct timespec t0;
    unsigned long polls = 0;
    double el;

    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (;;) {
        polls++;
        if (!pe_is_busy(x, y)) {
            el = elapsed_since(&t0);
            printf("   PE (%d,%d) idle after %.3f s (%lu polls)\n", x, y, el, polls);
            return 0;
        }
        if ((el = elapsed_since(&t0)) > timeout_s) break;
    }
    fprintf(stderr, "ERROR: PE (%d,%d) still busy after %.3f s.\n", x, y, el);
    return -1;
}

static int any_pe_busy(void)
{
    uint32_t w[NUM_WORDS];
    int i;

    read_map(w);
    for (i = 0; i < NUM_WORDS; i++)
        if (w[i])
            return 1;
    return 0;
}

/* Same format as print_pe_grid() in the C-simulation testbench. */
static void print_grid(void)
{
    int x, y;
    printf("   PE Occupancy Map:\n");
    for (y = 0; y < DIM_Y; y++) {
        printf("   |");
        for (x = 0; x < DIM_X; x++)
            printf("%s", pe_is_busy(x, y) ? "[]" : " .");
        printf("|\n");
    }
}

/* ---------------------------------------------------------------------------
 * Interactive shell
 * ------------------------------------------------------------------------- */
static void help(void)
{
    printf("  run c <cluster> <bank> <sec>    dispatch a cluster\n"
           "  run p <x> <y> <bank> <sec>      dispatch a single PE\n"
           "  reset                           reset every PE, spares included\n"
           "  map                             print the occupancy map\n"
           "  layout                          print the cluster map\n"
           "  load <file>                     re-read a layout file and upload it\n"
           "  wait <x> <y>                    block until a PE goes idle\n"
           "  quit\n"
           "dispatches return immediately, so you can overlap them.\n"
           "up/down recalls previous commands.\n");
}

/* Returns 1 to leave the shell. */
static int do_line(const char *line)
{
    char a[8], path[256];
    int b, c, x, y;
    double s;

    if (sscanf(line, " run c %d %d %lf", &c, &b, &s) == 3) {
        if (c < 0 || c >= MAX_CLUSTERS || !g_layout.declared[c]) {
            fprintf(stderr, "no cluster %d in the current layout -- try `layout`\n", c);
            return 0;
        }
        printf("cluster %d -> bank %d, %.3f s\n", c, b, s);
        run_and_report(0, 0, 0, c, b, SECONDS(s));
    } else if (sscanf(line, " run p %d %d %d %lf", &x, &y, &b, &s) == 4) {
        if (!in_grid(x, y)) {
            fprintf(stderr, "PE (%d,%d) is off the %dx%d grid\n", x, y, DIM_X, DIM_Y);
            return 0;
        }
        if (g_layout.cluster[y][x] == CLUSTER_SPARE)
            printf("note: PE (%d,%d) is a spare -- it will refuse this\n", x, y);
        printf("PE (%d,%d) -> bank %d, %.3f s\n", x, y, b, s);
        run_and_report(1, x, y, g_layout.cluster[y][x], b, SECONDS(s));
    } else if (sscanf(line, " wait %d %d", &x, &y) == 2) {
        if (!in_grid(x, y))
            fprintf(stderr, "PE (%d,%d) is off the %dx%d grid\n", x, y, DIM_X, DIM_Y);
        else
            wait_until_idle(x, y, 120.0);
    } else if (sscanf(line, " load %255s", path) == 1) {
        struct pm_layout l;
        char err[256];

        if (any_pe_busy()) {
            fprintf(stderr, "PEs are still busy -- `reset` first, or wait\n");
            return 0;
        }
        if (layout_parse(path, &l, err, sizeof(err)) != 0) {
            fprintf(stderr, "%s\n", err);
            return 0;
        }
        apply_layout(&l);
    } else if (sscanf(line, " %7s", a) == 1) {
        if (!strcmp(a, "map"))        print_grid();
        else if (!strcmp(a, "layout")) layout_print(&g_layout);
        else if (!strcmp(a, "reset")) {
            /* CLUSTER_ALL, not one command per cluster: with a layout file the
             * cluster ids are not known in advance, and spares belong to none. */
            issue_command(PM_RESET, TARGET_CLUSTER, 0, 0, CLUSTER_ALL, 0, 0);
            printf("grid reset.\n");
        }
        else if (!strcmp(a, "help"))  help();
        else if (!strcmp(a, "quit") || !strcmp(a, "exit")) return 1;
        else fprintf(stderr, "unknown command '%s' -- try `help`\n", a);
    }
    return 0;
}

static void shell(void)
{
    printf("type `help` for commands.\n");
    for (;;) {
        char *line = readline("pm> ");
        int quit;

        if (!line) { printf("\n"); break; }   /* ^D */
        if (*line) add_history(line);
        quit = do_line(line);
        free(line);
        if (quit) break;
    }
}

static void usage(const char *argv0)
{
    fprintf(stderr, "usage: %s [-c <layout file>]\n"
                    "  -c   cluster layout to upload (default %s)\n",
            argv0, DEFAULT_LAYOUT_FILE);
}

int main(int argc, char **argv)
{
    const char *cfg_path = DEFAULT_LAYOUT_FILE;
    int cfg_explicit = 0;
    struct pm_layout layout;
    char err[256];
    int rc = 0, fd, i;

    for (i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "-c") && i + 1 < argc) {
            cfg_path = argv[++i];
            cfg_explicit = 1;
        } else {
            usage(argv[0]);
            return 1;
        }
    }

    /* Parse before touching the hardware: a typo in the layout file should cost
     * nothing, and the error is easier to read without register noise around it. */
    if (layout_parse(cfg_path, &layout, err, sizeof(err)) != 0) {
        if (!cfg_explicit) {
            /* No file installed is a normal state, and the hardware's own
             * fallback is this same split, so nothing is actually uploaded. */
            fprintf(stderr, "%s\n", err);
            fprintf(stderr, "Falling back to the built-in left/right split.\n");
            layout_default(&layout);
        } else {
            fprintf(stderr, "%s\n", err);
            return 1;
        }
    } else {
        printf("Layout: %s\n", cfg_path);
    }

    fd = open("/dev/mem", O_RDWR | O_SYNC);
    if (fd < 0) {
        fprintf(stderr, "open(/dev/mem): %s\n", strerror(errno));
        return 1;
    }

    regs = mmap(NULL, PM_MAP_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED,
                fd, (off_t)PM_BASE_ADDR);
    if (regs == MAP_FAILED) {
        fprintf(stderr, "mmap(0x%lx): %s\n", PM_BASE_ADDR, strerror(errno));
        close(fd);
        return 1;
    }
    printf("Mapped program_manager_top at 0x%lx\n", PM_BASE_ADDR);

    if (bus_selftest() != 0) { rc = 1; goto out; }

    /* Clear anything a previous session left in flight before re-clustering
     * underneath it. Not required for correctness -- a config write does not
     * disturb a countdown -- but a PE still running under the old layout would
     * make the first `map` confusing. */
    printf("Resetting grid...\n");
    issue_command(PM_RESET, TARGET_CLUSTER, 0, 0, CLUSTER_ALL, 0, 0);

    apply_layout(&layout);
    print_grid();

    shell();

out:
    munmap((void *)regs, PM_MAP_SIZE);
    close(fd);
    return rc;
}
