/*
 * pm-app -- userspace driver for the PE-array program manager on VCU128/MicroBlaze.
 *
 * program_manager_top is a free-running (ap_ctrl_none) HLS kernel with an
 * AXI-Lite slave and an AXI4-Stream instruction port: no ap_start to assert, no
 * interrupt to wait on. It begins evaluating the grid the moment reset releases.
 * All we do is write a command, strobe valid, and poll the busy bitmap.
 *
 * The register window is a plain mmap of /dev/mem at the IP's base address.
 * There is no interrupt, so UIO would buy nothing over this.
 *
 * Two runtime tables live in the manager and are uploaded from here at startup:
 * which cluster each PE belongs to, and which kernel is resident in each of its
 * banks. Instructions themselves do not come through this file's register
 * window -- they are DMA'd into the manager's stream port by dma.c.
 *
 * This mirrors the Alveo host in HW_prototype/boards/u280/host_runtime.cpp and
 * the C-simulation testbench in vitis_hls/program_manager/test/main_csim.cpp --
 * the occupancy map it prints should match what `make csim` prints for the same
 * sequence.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <sys/mman.h>
#include <time.h>
#include <readline/readline.h>
#include <readline/history.h>

/* -------------------------------------------------------------------------
 * REGISTER OFFSETS -- must match the HLS-generated header:
 *   vitis_hls/IPs/program_manager/drivers/program_manager_top_v1_0/src/
 *       xprogram_manager_top_hw.h   (Vitis HLS 2024.2)
 *
 * Transcribed from the header regenerated by the `make ip` that built the
 * current bitstream. The layout is worth understanding, because guessing it
 * wrong is easy:
 *
 *   - Inputs sit on 8-byte strides in declaration order, each with a reserved
 *     word after it (0x10..0x58 here).
 *   - busy_mask_out follows at 0x60 with its ap_vld at 0x64.
 *   - The ARRAYS come next, at 0x70 and 0x78 -- NOT after all the scalars.
 *   - The remaining output scalars land after the arrays on 16-byte strides:
 *     0x80, 0x90, 0xa0.
 *
 * So adding the stream port and the new registers moved busy_map_out_bits from
 * 0x60 to 0x70. Re-check this block against xprogram_manager_top_hw.h after any
 * change to the port list -- bus_selftest() below catches the gross case, not a
 * subtle one.
 * ------------------------------------------------------------------------- */
#define REG_MODE            0x10
#define REG_TARGET_MODE     0x18
#define REG_PE_X            0x20
#define REG_PE_Y            0x28
#define REG_CLUSTER_ID      0x30
#define REG_BANK_ID         0x38
#define REG_KERNEL_ID       0x40
#define REG_INSTR_COUNT     0x48
#define REG_CYCLES          0x50
#define REG_VALID           0x58
#define REG_BUSY_MASK       0x60   /* 0x64 = busy_mask_out ap_vld (clear on read) */
#define REG_BUSY_MAP_BASE   0x70   /* busy_map_out_bits[2],   0x70-0x77 */
#define REG_KERNEL_MAP_BASE 0x78   /* kernel_map_out_bits[2], 0x78-0x7f */
#define REG_CFG_STATUS      0x80
#define REG_LOAD_STATUS     0x90
#define REG_LOAD_LAST       0xa0

/* cfg_status: the table entry pe_x/pe_y/bank_id currently address, plus what that
 * PE is executing. The resident-bank count cannot exceed MAX_BANKS, so it lives in
 * three bits and leaves a whole byte for the running kernel -- which is why adding
 * that field cost no new register and moved no offset. */
#define CFG_STATUS_LOADED   0x80000000u   /* the host's tables are in force */
#define CFG_STATUS_BUSY     0x40000000u
#define CFG_STATUS_IN_LOAD  0x20000000u   /* this PE is in the open transfer */
#define CFG_TAG(s)          ((s) & 0xffu)          /* kernel in the named bank */
#define CFG_CLUSTER(s)      (((s) >> 8) & 0xffu)
#define CFG_RUNNING(s)      (((s) >> 16) & 0xffu)  /* 0 = idle */
#define CFG_RESIDENT(s)     (((s) >> 24) & 0x7u)

/* load_status: the transfer in flight, or the last one attempted. */
#define LOAD_ACTIVE         0x80000000u
#define LOAD_REFUSED        0x40000000u   /* a target PE was busy: nothing opened */
#define LOAD_SHORT          0x20000000u   /* stream ended before instr_count */
#define LOAD_OVERRUN        0x10000000u
#define LOAD_BEATS(s)       ((s) & 0x00ffffffu)

/* Mirrors the enums in vitis_hls/program_manager/include/dispatch.hpp */
enum { PM_IDLE = 0, PM_RUN = 1, PM_RESET = 2, PM_CONFIG = 3,
       PM_LOAD = 4, PM_RUN_KERNEL = 5, PM_LOAD_ABORT = 6 };
enum { TARGET_SINGLE_PE = 0, TARGET_CLUSTER = 1 };

/* Under PM_CONFIG, target_mode has no targeting meaning and selects the sub-op. */
enum { CFG_CLUSTER_OP = 0, CFG_KERNEL_OP = 1 };

/* Under PM_CONFIG, pe_x = CFG_COMMIT means "publish the tables written so far"
 * rather than "configure PE 255". Uploading and publishing are separate so the
 * grid never dispatches against a half-written table. */
#define CFG_COMMIT 255

/* DIM_X / DIM_Y / MAX_BANKS / NUM_CLUSTERS come from pm_layout.h, which is
 * generated by `make layout-header` in vitis_hls/ from the same GRID_DIM the
 * bitstream was built with. Do not redefine them here -- that is exactly the
 * drift the generated header exists to prevent. */
#include "pm_layout.h"
#include "layout.h"
#include "dma.h"

#define DEFAULT_LAYOUT_FILE "/etc/pm-layout.conf"

#define NUM_WORDS ((DIM_X * DIM_Y + 31) / 32)

/* /pl-bus/program_manager_top@40010000, reg = <0x40010000 0x10000> */
#define PM_BASE_ADDR 0x40010000UL
#define PM_MAP_SIZE  0x1000UL

/* 100 MHz fabric clock (vivado/VCU128_microblaze_bd.tcl), but the free-running
 * loop synthesized at II=3 (see VITIS_LOOP_111_1 in csynth.rpt), so the PE
 * countdown advances once every three clocks. This went from 2 to 3 when the
 * residency table and the stream port landed -- re-check it after any HLS change,
 * because it is the only thing converting `run ... <sec>` into cycles. */
#define PM_CLK_HZ    100000000UL
#define PM_LOOP_II   3UL
#define PM_TICK_HZ   (PM_CLK_HZ / PM_LOOP_II)
#define SECONDS(s)   ((uint32_t)(PM_TICK_HZ * (s)))

static volatile uint32_t *regs;

/* The layout currently in force in the hardware. Everything host-side that used
 * to assume the compiled-in left/right split now reads this instead. */
static struct pm_layout g_layout;

/* The instruction path. Optional: if it fails to open, everything except
 * streaming still works. */
static struct pm_dma g_dma;
static int g_dma_ok;

static void reg_write(uint32_t off, uint32_t val) { regs[off / 4] = val; }
static uint32_t reg_read(uint32_t off)            { return regs[off / 4]; }

/* ---------------------------------------------------------------------------
 * Command layer
 * ------------------------------------------------------------------------- */
static void issue_command(uint8_t mode, uint8_t target_mode,
                          uint8_t pe_x, uint8_t pe_y, uint8_t cluster_id,
                          uint8_t bank_id, uint8_t kernel_id,
                          uint32_t instr_count, uint32_t cycles)
{
    reg_write(REG_MODE,        mode);
    reg_write(REG_TARGET_MODE, target_mode);
    reg_write(REG_PE_X,        pe_x);
    reg_write(REG_PE_Y,        pe_y);
    reg_write(REG_CLUSTER_ID,  cluster_id);
    reg_write(REG_BANK_ID,     bank_id);
    reg_write(REG_KERNEL_ID,   kernel_id);
    reg_write(REG_INSTR_COUNT, instr_count);
    reg_write(REG_CYCLES,      cycles);

    /* The kernel edge-detects valid_signal; only the 0->1 transition latches a
     * command. Two AXI-Lite writes are many kernel cycles apart, so the high
     * period is comfortably long enough to be sampled. */
    reg_write(REG_VALID, 1);
    reg_write(REG_VALID, 0);
}

/* Point pe_x/pe_y/bank_id at one table entry and read it back. No command is
 * issued -- cfg_status is a live view of whatever those registers address. */
static uint32_t probe_bank(int bank)
{
    reg_write(REG_BANK_ID, (uint32_t)bank);
    return reg_read(REG_CFG_STATUS);
}

static uint32_t probe_entry(int x, int y, int bank)
{
    reg_write(REG_PE_X, (uint32_t)x);
    reg_write(REG_PE_Y, (uint32_t)y);
    return probe_bank(bank);
}

/* cycles is Read/Write, so a readback distinguishes "bus is dead" from
 * "everything works but the dispatch was too short to catch". cfg_status is
 * Read-only and moves with pe_x, which catches the other likely failure: offsets
 * that no longer match the regenerated header. */
static int bus_selftest(void)
{
    static const uint32_t pat[] = { 0xdeadbeefu, 0x55555555u, 0u };
    unsigned i;
    uint32_t a, b;

    for (i = 0; i < sizeof(pat) / sizeof(pat[0]); i++) {
        uint32_t rb;
        reg_write(REG_CYCLES, pat[i]);
        rb = reg_read(REG_CYCLES);
        if (rb != pat[i]) {
            fprintf(stderr, "AXI-Lite readback failed at 0x%02x: wrote 0x%08x, read 0x%08x\n",
                    REG_CYCLES, pat[i], rb);
            fprintf(stderr, "the IP is not responding -- check the bitstream is loaded "
                            "and the interconnect address map matches 0x%lx.\n", PM_BASE_ADDR);
            return -1;
        }
    }

    /* Before any upload both halves of the grid differ in the compiled-in
     * fallback, so cfg_status must not read the same for both. */
    a = probe_entry(0, 0, 0);
    b = probe_entry(DIM_X - 1, 0, 0);
    if (a == b) {
        fprintf(stderr,
                "WARNING: cfg_status (0x%02x) reads 0x%08x for both (0,0) and (%d,0).\n"
                "         The register offsets in this file are probably stale -- check\n"
                "         xprogram_manager_top_hw.h from the last `make ip`. Dispatch may\n"
                "         still work; the table readback will not.\n",
                REG_CFG_STATUS, a, DIM_X - 1);
    }
    printf("AXI-Lite readback OK.\n");
    return 0;
}

static int pe_is_busy(int x, int y)
{
    int flat = y * DIM_X + x;
    uint32_t word = reg_read(REG_BUSY_MAP_BASE + (flat / 32) * 4);
    return (word >> (flat % 32)) & 1u;
}

static void read_map(uint32_t *w)
{
    int i;
    for (i = 0; i < NUM_WORDS; i++)
        w[i] = reg_read(REG_BUSY_MAP_BASE + i * 4);
}

/* Which PEs hold this kernel, in any bank. One read of the manager's comparator
 * network instead of walking all DIM_X*DIM_Y*MAX_BANKS tags. */
static void read_kernel_map(uint8_t kernel, uint32_t *w)
{
    int i;
    reg_write(REG_KERNEL_ID, kernel);
    for (i = 0; i < NUM_WORDS; i++)
        w[i] = reg_read(REG_KERNEL_MAP_BASE + i * 4);
}

static int map_bit(const uint32_t *w, int x, int y)
{
    int flat = y * DIM_X + x;
    return (w[flat / 32] >> (flat % 32)) & 1u;
}

static int in_grid(int x, int y)
{
    return x >= 0 && x < DIM_X && y >= 0 && y < DIM_Y;
}

static void print_bitmap(const uint32_t *w, const char *title)
{
    int x, y;
    printf("   %s\n", title);
    for (y = 0; y < DIM_Y; y++) {
        printf("   |");
        for (x = 0; x < DIM_X; x++)
            printf("%s", map_bit(w, x, y) ? "[]" : " .");
        printf("|\n");
    }
}

/* ---------------------------------------------------------------------------
 * Table upload
 *
 * Cluster membership and kernel residency are no longer functions of position --
 * they are whatever the layout file says. The manager holds both in registers;
 * we write them one entry at a time and then commit.
 * ------------------------------------------------------------------------- */
static void push_layout(const struct pm_layout *l)
{
    int x, y, b;

    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            issue_command(PM_CONFIG, CFG_CLUSTER_OP, (uint8_t)x, (uint8_t)y,
                          l->cluster[y][x], 0, 0, 0, 0);
            for (b = 0; b < MAX_BANKS; b++)
                issue_command(PM_CONFIG, CFG_KERNEL_OP, (uint8_t)x, (uint8_t)y,
                              0, (uint8_t)b, l->kernel[y][x][b], 0, 0);
        }
    }

    issue_command(PM_CONFIG, CFG_CLUSTER_OP, CFG_COMMIT, 0, 0, 0, 0, 0, 0);
}

/* Reads the tables back out of the hardware rather than assuming the writes
 * landed. Returns the number of mismatches. */
static int verify_layout(const struct pm_layout *l)
{
    int x, y, b, bad = 0;
    uint32_t st = 0;

    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            for (b = 0; b < MAX_BANKS; b++) {
                st = probe_entry(x, y, b);
                if (CFG_TAG(st) == l->kernel[y][x][b] &&
                    (b > 0 || CFG_CLUSTER(st) == l->cluster[y][x]))
                    continue;
                if (bad < 4)
                    fprintf(stderr, "   PE (%d,%d) bank %d: wrote cluster %u kernel %u, "
                                    "read back cluster %u kernel %u\n",
                            x, y, b, l->cluster[y][x], l->kernel[y][x][b],
                            (unsigned)CFG_CLUSTER(st), (unsigned)CFG_TAG(st));
                bad++;
            }
        }
    }

    if (!(st & CFG_STATUS_LOADED)) {
        fprintf(stderr, "   commit did not take: cfg_loaded is still clear\n");
        bad++;
    }
    return bad;
}

/* Upload, verify, and adopt. A verification failure is reported loudly but not
 * treated as fatal: the most likely cause is REG_CFG_STATUS being at the wrong
 * offset, which does not affect dispatch at all, and refusing to start would
 * leave no way to investigate from the board. */
static void apply_layout(const struct pm_layout *l)
{
    int bad, total = DIM_X * DIM_Y * MAX_BANKS;

    push_layout(l);
    bad = verify_layout(l);
    g_layout = *l;

    if (bad) {
        fprintf(stderr, "WARNING: %d of %d table entries did not read back as written.\n"
                        "         If ALL of them differ, REG_CFG_STATUS (0x%02x) is "
                        "probably wrong --\n"
                        "         check xprogram_manager_top_hw.h. Dispatch is "
                        "unaffected either way;\n"
                        "         use `run` and `map` to see what the grid actually "
                        "does.\n",
                bad, total, REG_CFG_STATUS);
    } else {
        printf("Tables uploaded and verified (%d entries).\n", total);
    }
    layout_print(l);
}

/* ---------------------------------------------------------------------------
 * Instruction streaming
 *
 * MODE_LOAD opens the transfer and the DMA then pushes the words in. The order
 * matters: beats that arrive before the manager has a transfer open are dropped
 * on the floor, so the command always goes first.
 * ------------------------------------------------------------------------- */
static int stream_kernel(int cluster, int px, int py, int bank, uint8_t kernel,
                         uint32_t n, uint32_t run_cycles, const char *image)
{
    char err[256];
    uint32_t st;
    long got;
    int single = (cluster < 0);

    if (!g_dma_ok) {
        fprintf(stderr, "no DMA path: cannot stream instructions\n");
        return -1;
    }

    got = image ? pm_dma_fill_file(&g_dma, image, n, err, sizeof(err))
                : pm_dma_fill_generated(&g_dma, kernel, n, err, sizeof(err));
    if (got < 0) {
        fprintf(stderr, "%s\n", err);
        return -1;
    }

    issue_command(PM_LOAD, single ? TARGET_SINGLE_PE : TARGET_CLUSTER,
                  (uint8_t)(single ? px : 0), (uint8_t)(single ? py : 0),
                  (uint8_t)(single ? 0 : cluster), (uint8_t)bank, kernel, n, run_cycles);

    st = reg_read(REG_LOAD_STATUS);
    if (st & LOAD_REFUSED) {
        fprintf(stderr, "   refused: a targeted PE is busy (reset or wait first)\n");
        return -1;
    }
    if (!(st & LOAD_ACTIVE)) {
        fprintf(stderr, "   the manager did not open a transfer (load_status 0x%08x)\n", st);
        return -1;
    }

    if (pm_dma_send(&g_dma, n, err, sizeof(err)) != 0) {
        fprintf(stderr, "%s\n", err);
        fprintf(stderr, "   aborting the open transfer so the PEs are not left held\n");
        issue_command(PM_LOAD_ABORT, TARGET_SINGLE_PE, 0, 0, 0, 0, 0, 0, 0);
        return -1;
    }

    st = reg_read(REG_LOAD_STATUS);
    if (st & LOAD_SHORT) {
        fprintf(stderr, "   short: %u of %u instructions arrived, nothing committed\n",
                LOAD_BEATS(st), n);
        return -1;
    }
    if (st & LOAD_OVERRUN)
        fprintf(stderr, "   overrun: more instructions arrived than the %u declared\n", n);
    if (st & LOAD_ACTIVE) {
        fprintf(stderr, "   transfer still open after the DMA finished -- no TLAST?\n");
        return -1;
    }

    printf("   %u instructions delivered, last word 0x%08x\n",
           LOAD_BEATS(st), reg_read(REG_LOAD_LAST));

    /* Keep the host mirror in step with what the hardware now holds. */
    if (single) {
        g_layout.kernel[py][px][bank] = kernel;
    } else {
        int x, y;
        for (y = 0; y < DIM_Y; y++)
            for (x = 0; x < DIM_X; x++)
                if (g_layout.cluster[y][x] == cluster)
                    g_layout.kernel[y][x][bank] = kernel;
    }
    return 0;
}

/* At startup, actually push the instructions the layout file declares. One
 * broadcast per (cluster, bank) rather than one transfer per PE: the data is
 * identical across a cluster, so 32 PEs cost one transfer. */
static void preload_kernels(const struct pm_layout *l)
{
    int c, b, x, y;

    if (!g_dma_ok)
        return;

    for (c = 0; c < MAX_CLUSTERS; c++) {
        int fx = -1, fy = -1;
        if (!l->declared[c])
            continue;
        for (y = 0; y < DIM_Y && fx < 0; y++)
            for (x = 0; x < DIM_X && fx < 0; x++)
                if (l->cluster[y][x] == c) { fx = x; fy = y; }
        if (fx < 0)
            continue;

        for (b = 0; b < MAX_BANKS; b++) {
            uint8_t k = l->kernel[fy][fx][b];
            const struct kernel_info *ki;
            if (k == KERNEL_NONE)
                continue;
            ki = &l->kern[k];
            if (ki->src == KSRC_NONE)
                continue;      /* tag declared, nothing to stream */
            printf("Preloading kernel %u into cluster %d bank %d (%u instructions)...\n",
                   k, c, b, ki->n_instr);
            stream_kernel(c, 0, 0, b, k, ki->n_instr, 0,
                          ki->src == KSRC_IMAGE ? ki->image : NULL);
        }
    }
}

/* ---------------------------------------------------------------------------
 * Dispatch
 * ------------------------------------------------------------------------- */
/* The IP reports no accept/reject status: a busy PE ignores a command and an
 * empty bank is refused, both silently. Sampling the map either side of the
 * strobe separates the cases exactly -- a PE that was idle and is now busy
 * accepted, anything else did not. Only valid for dispatches long enough to
 * outlive the readback; sub-millisecond runs look refused. */
static void report_accept(const uint32_t *before, const uint32_t *after,
                          int single, int tx, int ty, int cluster)
{
    int x, y, started = 0, was_busy = 0, refused = 0;

    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            int targeted = single ? (x == tx && y == ty)
                                  : (g_layout.cluster[y][x] == cluster);
            if (!targeted)
                continue;
            if (map_bit(before, x, y))      was_busy++;
            else if (map_bit(after, x, y))  started++;
            else                            refused++;
        }
    }

    printf("   accepted %d", started);
    if (was_busy) printf(", %d already busy", was_busy);
    if (refused)  printf(", %d refused (kernel not resident, or a spare PE)", refused);
    printf("\n");
}

/* Wraps issue_command with the before/after sampling. */
static void run_and_report(int single, int x, int y, int cluster,
                           int bank, uint32_t cycles)
{
    uint32_t before[NUM_WORDS], after[NUM_WORDS];

    read_map(before);
    issue_command(PM_RUN, single ? TARGET_SINGLE_PE : TARGET_CLUSTER,
                  (uint8_t)x, (uint8_t)y, (uint8_t)cluster, (uint8_t)bank, 0, 0, cycles);
    read_map(after);
    report_accept(before, after, single, x, y, cluster);
}

/* The resident case: name the kernel and let each PE find its own slot. */
static void run_kernel_and_report(int cluster, uint8_t kernel, uint32_t cycles)
{
    uint32_t before[NUM_WORDS], after[NUM_WORDS];

    read_map(before);
    issue_command(PM_RUN_KERNEL, TARGET_CLUSTER, 0, 0, (uint8_t)cluster,
                  0, kernel, 0, cycles);
    read_map(after);
    report_accept(before, after, 0, 0, 0, cluster);
}

static double elapsed_since(const struct timespec *t0)
{
    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    return (now.tv_sec - t0->tv_sec) + (now.tv_nsec - t0->tv_nsec) / 1e9;
}

/* Bounded, unlike the Alveo host's unbounded spin. Reports how long the PE was
 * actually seen busy, which is what tells you whether a dispatch was observable
 * at all. */
static int wait_until_idle(int x, int y, double timeout_s)
{
    struct timespec t0;
    unsigned long polls = 0;
    double el;

    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (;;) {
        polls++;
        if (!pe_is_busy(x, y)) {
            el = elapsed_since(&t0);
            printf("   PE (%d,%d) idle after %.3f s (%lu polls)\n", x, y, el, polls);
            return 0;
        }
        if ((el = elapsed_since(&t0)) > timeout_s) break;
    }
    fprintf(stderr, "ERROR: PE (%d,%d) still busy after %.3f s.\n", x, y, el);
    return -1;
}

static int any_pe_busy(void)
{
    uint32_t w[NUM_WORDS];
    int i;

    read_map(w);
    for (i = 0; i < NUM_WORDS; i++)
        if (w[i])
            return 1;
    return 0;
}

/* Same format as print_pe_grid() in the C-simulation testbench. */
static void print_grid(void)
{
    int x, y;
    printf("   PE Occupancy Map:\n");
    for (y = 0; y < DIM_Y; y++) {
        printf("   |");
        for (x = 0; x < DIM_X; x++)
            printf("%s", pe_is_busy(x, y) ? "[]" : " .");
        printf("|\n");
    }
}

/* The four tags of one PE, read out of the hardware rather than the mirror. */
static void print_banks(int x, int y)
{
    int b;
    uint32_t st = probe_entry(x, y, 0);

    printf("   PE (%d,%d): cluster ", x, y);
    if (CFG_CLUSTER(st) == CLUSTER_SPARE) printf("spare");
    else                                  printf("%u", (unsigned)CFG_CLUSTER(st));
    printf(", %u resident bank(s)", (unsigned)CFG_RESIDENT(st));
    if (st & CFG_STATUS_BUSY) printf(", running kernel %u", (unsigned)CFG_RUNNING(st));
    printf("\n");
    for (b = 0; b < MAX_BANKS; b++) {
        st = probe_entry(x, y, b);
        printf("     bank %d: ", b);
        if (CFG_TAG(st)) printf("kernel %u\n", (unsigned)CFG_TAG(st));
        else             printf("empty\n");
    }
    if (st & CFG_STATUS_IN_LOAD)
        printf("     (a transfer into this PE is open)\n");
}

/* The whole array in one pass, read from hardware: membership, residency, and
 * what each PE is executing right now. Unlike `layout`, which prints the parsed
 * file, nothing here comes from the host's mirror -- a disagreement between the
 * two is itself the useful signal.
 *
 * 64 PEs x (2 address writes + 4 bank read pairs) = 640 AXI-Lite transactions,
 * a few milliseconds. Fine for a command a human types. */
static void print_status(void)
{
    uint8_t clus[DIM_Y][DIM_X], run[DIM_Y][DIM_X], tag[DIM_Y][DIM_X][MAX_BANKS];
    struct { uint8_t cluster, tag[MAX_BANKS]; int n, fx, fy; } grp[DIM_X * DIM_Y];
    int x, y, b, g, ngrp = 0, nbusy = 0;

    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            reg_write(REG_PE_X, (uint32_t)x);
            reg_write(REG_PE_Y, (uint32_t)y);
            for (b = 0; b < MAX_BANKS; b++) {
                uint32_t st = probe_bank(b);
                tag[y][x][b] = CFG_TAG(st);
                if (b == 0) {
                    clus[y][x] = CFG_CLUSTER(st);
                    run[y][x]  = CFG_RUNNING(st);
                    if (st & CFG_STATUS_BUSY) nbusy++;
                }
            }
        }
    }

    printf("   Cluster map (x ->):\n");
    for (y = 0; y < DIM_Y; y++) {
        printf("   |");
        for (x = 0; x < DIM_X; x++)
            printf(" %c", layout_cluster_char(clus[y][x]));
        printf("|\n");
    }

    printf("   Running now (x ->):        . = idle\n");
    for (y = 0; y < DIM_Y; y++) {
        printf("   |");
        for (x = 0; x < DIM_X; x++) {
            if (run[y][x]) printf("%4u", (unsigned)run[y][x]);
            else           printf("   .");
        }
        printf("|\n");
    }

    /* Group by identical (cluster, tags) so a uniform grid is a few lines, while
     * a single-PE load that splits a cluster shows up as its own group instead of
     * being averaged away. */
    for (y = 0; y < DIM_Y; y++) {
        for (x = 0; x < DIM_X; x++) {
            for (g = 0; g < ngrp; g++)
                if (grp[g].cluster == clus[y][x] &&
                    !memcmp(grp[g].tag, tag[y][x], MAX_BANKS))
                    break;
            if (g == ngrp) {
                grp[g].cluster = clus[y][x];
                memcpy(grp[g].tag, tag[y][x], MAX_BANKS);
                grp[g].n = 0; grp[g].fx = x; grp[g].fy = y;
                ngrp++;
            }
            grp[g].n++;
        }
    }

    printf("   Residency (grouped):\n");
    for (g = 0; g < ngrp; g++) {
        if (grp[g].n == 1) printf("     PE (%d,%d)  ", grp[g].fx, grp[g].fy);
        else               printf("     %2d PEs    ", grp[g].n);
        if (grp[g].cluster == CLUSTER_SPARE) printf("spare      ");
        else                                 printf("cluster %-3u", (unsigned)grp[g].cluster);
        printf(" banks [");
        for (b = 0; b < MAX_BANKS; b++) {
            if (grp[g].tag[b]) printf("%4u", (unsigned)grp[g].tag[b]);
            else               printf("   -");
        }
        printf(" ]\n");
    }
    printf("   %d of %d PEs busy.\n", nbusy, DIM_X * DIM_Y);
}

/* ---------------------------------------------------------------------------
 * Interactive shell
 * ------------------------------------------------------------------------- */
static void help(void)
{
    printf("  run c <cluster> <bank> <sec>    dispatch a cluster by bank\n"
           "  run k <kernel> <cluster> <sec>  dispatch a cluster by kernel id\n"
           "  run p <x> <y> <bank> <sec>      dispatch a single PE\n"
           "  load <kernel> <opts>            stream instructions in over the DMA\n"
           "       instr <n>                    how many 64-bit words (required)\n"
           "       file <path>                  send a file instead of a dummy pattern\n"
           "       c <cluster> | p <x> <y>      where to put it (default: cluster 0)\n"
           "       bank <b>                     which slot (default: first free)\n"
           "       run <sec>                    start it as soon as it lands\n"
           "  where <kernel>                  which PEs hold a kernel\n"
           "  banks <x> <y>                   what one PE holds, read from hardware\n"
           "  reset                           reset every PE, spares included\n"
           "  abort                           tear down a stuck instruction transfer\n"
           "  map                             print the occupancy map\n"
           "  status                          whole array from hardware: clusters,\n"
           "                                  residency, and what is running now\n"
           "  layout                          print the parsed layout file\n"
           "  load-layout <file>              re-read a layout file and upload it\n"
           "  wait <x> <y>                    block until a PE goes idle\n"
           "  quit\n"
           "dispatches return immediately, so you can overlap them.\n"
           "up/down recalls previous commands.\n");
}

/* load <kernel> [instr <n>] [file <path>] [c <cluster>|p <x> <y>] [bank <b>] [run <sec>] */
static void do_load(const char *args)
{
    char buf[512], *save = NULL, *tok;
    long kernel = -1, n = -1, cluster = -1, px = -1, py = -1, bank = -1;
    double sec = 0.0;
    const char *image = NULL;
    char image_buf[MAX_IMAGE_PATH];

    snprintf(buf, sizeof(buf), "%s", args);
    tok = strtok_r(buf, " \t\r\n", &save);
    if (!tok || (kernel = strtol(tok, NULL, 10)) < 1 || kernel > MAX_KERNEL_ID) {
        fprintf(stderr, "load needs a kernel id in 1..%d\n", MAX_KERNEL_ID);
        return;
    }

    while ((tok = strtok_r(NULL, " \t\r\n", &save))) {
        char *val = strtok_r(NULL, " \t\r\n", &save);
        if (!val) { fprintf(stderr, "'%s' needs a value\n", tok); return; }

        if      (!strcmp(tok, "instr")) n       = strtol(val, NULL, 10);
        else if (!strcmp(tok, "bank"))  bank    = strtol(val, NULL, 10);
        else if (!strcmp(tok, "c"))     cluster = strtol(val, NULL, 10);
        else if (!strcmp(tok, "run"))   sec     = strtod(val, NULL);
        else if (!strcmp(tok, "file")) {
            snprintf(image_buf, sizeof(image_buf), "%s", val);
            image = image_buf;
        } else if (!strcmp(tok, "p")) {
            char *val2 = strtok_r(NULL, " \t\r\n", &save);
            if (!val2) { fprintf(stderr, "'p' needs x and y\n"); return; }
            px = strtol(val, NULL, 10);
            py = strtol(val2, NULL, 10);
        } else {
            fprintf(stderr, "unknown option '%s' -- try `help`\n", tok);
            return;
        }
    }

    if (n < 1) {
        fprintf(stderr, "load needs `instr <n>`: the manager is told the count up "
                        "front and refuses to commit a short transfer\n");
        return;
    }
    if (px >= 0 && cluster >= 0) {
        fprintf(stderr, "give either `c <cluster>` or `p <x> <y>`, not both\n");
        return;
    }
    if (px >= 0 && !in_grid((int)px, (int)py)) {
        fprintf(stderr, "PE (%ld,%ld) is off the %dx%d grid\n", px, py, DIM_X, DIM_Y);
        return;
    }
    if (px < 0 && cluster < 0)
        cluster = 0;
    if (cluster >= 0 && (cluster >= MAX_CLUSTERS || !g_layout.declared[cluster])) {
        fprintf(stderr, "no cluster %ld in the current layout -- try `layout`\n", cluster);
        return;
    }

    /* Placement: read the array status now rather than trusting the mirror, and
     * pick a slot from it. First free bank, else bank 0 -- eviction policy lives
     * here, not in hardware. */
    if (bank < 0) {
        int fx = (int)px, fy = (int)py, b;
        if (px < 0) {
            int x, y;
            fx = -1;
            for (y = 0; y < DIM_Y && fx < 0; y++)
                for (x = 0; x < DIM_X && fx < 0; x++)
                    if (g_layout.cluster[y][x] == cluster) { fx = x; fy = y; }
            if (fx < 0) { fprintf(stderr, "cluster %ld has no PEs\n", cluster); return; }
        }
        for (b = 0; b < MAX_BANKS; b++)
            if (CFG_TAG(probe_entry(fx, fy, b)) == KERNEL_NONE) break;
        bank = (b < MAX_BANKS) ? b : 0;
        printf("   placing kernel %ld in bank %ld%s\n", kernel, bank,
               (b < MAX_BANKS) ? " (first free)" : " (no free bank: evicting bank 0)");
    }
    if (bank < 0 || bank >= MAX_BANKS) {
        fprintf(stderr, "bank must be 0..%d\n", MAX_BANKS - 1);
        return;
    }

    if (px >= 0)
        printf("load kernel %ld -> PE (%ld,%ld) bank %ld, %ld instructions\n",
               kernel, px, py, bank, n);
    else
        printf("load kernel %ld -> cluster %ld bank %ld, %ld instructions\n",
               kernel, cluster, bank, n);

    stream_kernel((int)cluster, (int)px, (int)py, (int)bank, (uint8_t)kernel,
                  (uint32_t)n, sec > 0.0 ? SECONDS(sec) : 0, image);
}

/* Returns 1 to leave the shell. */
static int do_line(const char *line)
{
    char a[16], path[256];
    int b, c, k, x, y;
    double s;
    const char *p;

    /* Skip leading blanks once, so the prefix tests below are plain strncmp.
     * They used to be sscanf(" load %n", &n): note that sscanf leaves %n
     * UNTOUCHED when the literal fails to match and still returns 0, so that
     * guard read an uninitialized int and swallowed every short command. */
    for (p = line; *p == ' ' || *p == '\t'; p++)
        ;

    if (sscanf(line, " run c %d %d %lf", &c, &b, &s) == 3) {
        if (c < 0 || c >= MAX_CLUSTERS || !g_layout.declared[c]) {
            fprintf(stderr, "no cluster %d in the current layout -- try `layout`\n", c);
            return 0;
        }
        printf("cluster %d -> bank %d, %.3f s\n", c, b, s);
        run_and_report(0, 0, 0, c, b, SECONDS(s));
    } else if (sscanf(line, " run k %d %d %lf", &k, &c, &s) == 3) {
        if (k < 1 || k > MAX_KERNEL_ID) {
            fprintf(stderr, "kernel id must be 1..%d\n", MAX_KERNEL_ID);
            return 0;
        }
        if (c < 0 || c >= MAX_CLUSTERS || !g_layout.declared[c]) {
            fprintf(stderr, "no cluster %d in the current layout -- try `layout`\n", c);
            return 0;
        }
        printf("cluster %d -> kernel %d, %.3f s\n", c, k, s);
        run_kernel_and_report(c, (uint8_t)k, SECONDS(s));
    } else if (sscanf(line, " run p %d %d %d %lf", &x, &y, &b, &s) == 4) {
        if (!in_grid(x, y)) {
            fprintf(stderr, "PE (%d,%d) is off the %dx%d grid\n", x, y, DIM_X, DIM_Y);
            return 0;
        }
        if (g_layout.cluster[y][x] == CLUSTER_SPARE)
            printf("note: PE (%d,%d) is a spare -- it will refuse this\n", x, y);
        else if (b >= 0 && b < MAX_BANKS && g_layout.kernel[y][x][b] == KERNEL_NONE)
            printf("note: PE (%d,%d) bank %d is empty -- it will refuse this\n", x, y, b);
        printf("PE (%d,%d) -> bank %d, %.3f s\n", x, y, b, s);
        run_and_report(1, x, y, g_layout.cluster[y][x], b, SECONDS(s));
    } else if (sscanf(line, " where %d", &k) == 1) {
        uint32_t w[NUM_WORDS];
        char title[64];
        read_kernel_map((uint8_t)k, w);
        snprintf(title, sizeof(title), "PEs holding kernel %d:", k);
        print_bitmap(w, title);
    } else if (sscanf(line, " banks %d %d", &x, &y) == 2) {
        if (!in_grid(x, y))
            fprintf(stderr, "PE (%d,%d) is off the %dx%d grid\n", x, y, DIM_X, DIM_Y);
        else
            print_banks(x, y);
    } else if (sscanf(line, " wait %d %d", &x, &y) == 2) {
        if (!in_grid(x, y))
            fprintf(stderr, "PE (%d,%d) is off the %dx%d grid\n", x, y, DIM_X, DIM_Y);
        else
            wait_until_idle(x, y, 120.0);
    } else if (sscanf(line, " load-layout %255s", path) == 1) {
        struct pm_layout l;
        char err[256];

        if (any_pe_busy()) {
            fprintf(stderr, "PEs are still busy -- `reset` first, or wait\n");
            return 0;
        }
        if (layout_parse(path, &l, err, sizeof(err)) != 0) {
            fprintf(stderr, "%s\n", err);
            return 0;
        }
        apply_layout(&l);
        preload_kernels(&l);
    } else if (!strncmp(p, "load ", 5) || !strncmp(p, "load\t", 5)) {
        do_load(p + 5);
    } else if (sscanf(line, " %15s", a) == 1) {
        if (!strcmp(a, "map"))         print_grid();
        else if (!strcmp(a, "status")) print_status();
        else if (!strcmp(a, "layout")) layout_print(&g_layout);
        else if (!strcmp(a, "abort")) {
            issue_command(PM_LOAD_ABORT, TARGET_SINGLE_PE, 0, 0, 0, 0, 0, 0, 0);
            printf("instruction transfer aborted.\n");
        }
        else if (!strcmp(a, "reset")) {
            /* CLUSTER_ALL, not one command per cluster: with a layout file the
             * cluster ids are not known in advance, and spares belong to none. */
            issue_command(PM_RESET, TARGET_CLUSTER, 0, 0, CLUSTER_ALL, 0, 0, 0, 0);
            printf("grid reset.\n");
        }
        else if (!strcmp(a, "help"))  help();
        else if (!strcmp(a, "quit") || !strcmp(a, "exit")) return 1;
        else fprintf(stderr, "unknown command '%s' -- try `help`\n", a);
    }
    return 0;
}

static void shell(void)
{
    printf("type `help` for commands.\n");
    for (;;) {
        char *line = readline("pm> ");
        int quit;

        if (!line) { printf("\n"); break; }   /* ^D */
        if (*line) add_history(line);
        quit = do_line(line);
        free(line);
        if (quit) break;
    }
}

static void usage(const char *argv0)
{
    fprintf(stderr, "usage: %s [-c <layout file>]\n"
                    "  -c   cluster layout to upload (default %s)\n",
            argv0, DEFAULT_LAYOUT_FILE);
}

int main(int argc, char **argv)
{
    const char *cfg_path = DEFAULT_LAYOUT_FILE;
    int cfg_explicit = 0;
    struct pm_layout layout;
    char err[256];
    int rc = 0, fd, i;

    for (i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "-c") && i + 1 < argc) {
            cfg_path = argv[++i];
            cfg_explicit = 1;
        } else {
            usage(argv[0]);
            return 1;
        }
    }

    /* Parse before touching the hardware: a typo in the layout file should cost
     * nothing, and the error is easier to read without register noise around it. */
    if (layout_parse(cfg_path, &layout, err, sizeof(err)) != 0) {
        if (!cfg_explicit) {
            /* No file installed is a normal state, and the hardware's own
             * fallback is this same split, so nothing is actually uploaded. */
            fprintf(stderr, "%s\n", err);
            fprintf(stderr, "Falling back to the built-in left/right split.\n");
            layout_default(&layout);
        } else {
            fprintf(stderr, "%s\n", err);
            return 1;
        }
    } else {
        printf("Layout: %s\n", cfg_path);
    }

    fd = open("/dev/mem", O_RDWR | O_SYNC);
    if (fd < 0) {
        fprintf(stderr, "open(/dev/mem): %s\n", strerror(errno));
        return 1;
    }

    regs = mmap(NULL, PM_MAP_SIZE, PROT_READ | PROT_WRITE, MAP_SHARED,
                fd, (off_t)PM_BASE_ADDR);
    if (regs == MAP_FAILED) {
        fprintf(stderr, "mmap(0x%lx): %s\n", PM_BASE_ADDR, strerror(errno));
        close(fd);
        return 1;
    }
    close(fd);
    printf("Mapped program_manager_top at 0x%lx\n", PM_BASE_ADDR);

    if (bus_selftest() != 0) { rc = 1; goto out; }

    /* The instruction path is optional: without it everything except streaming
     * still works, and saying so once is better than failing every load. */
    if (pm_dma_open(&g_dma, err, sizeof(err)) == 0) {
        g_dma_ok = 1;
    } else {
        fprintf(stderr, "WARNING: %s\n", err);
        fprintf(stderr, "         instruction streaming is unavailable; residency "
                        "tags can still be set from the layout file.\n");
    }

    /* Clear anything a previous session left in flight before re-clustering
     * underneath it. Not required for correctness -- a config write does not
     * disturb a countdown -- but a PE still running under the old layout would
     * make the first `map` confusing. */
    printf("Resetting grid...\n");
    issue_command(PM_RESET, TARGET_CLUSTER, 0, 0, CLUSTER_ALL, 0, 0, 0, 0);
    issue_command(PM_LOAD_ABORT, TARGET_SINGLE_PE, 0, 0, 0, 0, 0, 0, 0);

    apply_layout(&layout);
    preload_kernels(&layout);
    print_grid();

    shell();

out:
    if (g_dma_ok) pm_dma_close(&g_dma);
    munmap((void *)regs, PM_MAP_SIZE);
    return rc;
}
