/* Generated by `make layout-header` in vitis_hls/ -- do not edit by hand.
 * Keeps pm-app in step with the grid compiled into the bitstream. */
#ifndef PM_LAYOUT_H
#define PM_LAYOUT_H

#define DIM_X        8
#define DIM_Y        8
#define MAX_BANKS    4
#define NUM_CLUSTERS 2

#endif
